# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yXVIYzt821tq-SQQTGWWFDaTW7vj1AZ1

desafio
"""

banco = input("digite o nome do banco: ")
renda = float (input("renda mensal em %: "))
capitalInicial = float (input("capital inicial: "))
tempo = int (input("tempo de investimento em meses: "))

for i in range(0,tempo):
  rendaMensal = capitalInicial / 100 * renda
  dinheiro = capitalInicial + rendaMensal

print("no banco", banco, "você terá", "%.2f" %dinheiro, "ao final de um periodo de", tempo, "meses.")

"""desafio 2"""

h = float (input ("altura: "))
b = float (input ("base: "))

print ("A área do retangulo é igual a: ", b * h)
print ("A área do triangulo é igual a: ", b * h /2)